[package]
name = "arcane"
version = "0.1.0"
edition = "2021"
authors = ["Alex Vergara<pyzyryab@tutanota.com>"]


[dependencies]
arcane-macros = { path = "./macros" }
arcane-reflexion = { path = "../reflexion" }
arcane-ops = { path = "../ops" }