[package]
name = "arcane-reflexion"
version = "0.1.0"
edition = "2021"
authors = ["Alex Vergara<pyzyryab@tutanota.com>"]


[dependencies]
syn = { version = "1.0.86", features = ["full"] }

arcane-ops = { path = "../ops" }